### ISSUE TITLE
Sometimes unflushed buffer shows the last line in the next message

### ISSUE THREAD

**Issue by ghost** [EasyRPG/EV0002#4]
This happens rarely though.

**Comment by carstene1ns** [comment]
It seems this only happens with very long lines, for example if the issue title is too long or something.

**Comment by ghost** [comment]
I don't remember to see this issue anymore since some months, maybe is actually fixed on deps?

**Comment by carstene1ns** [comment]
Cinch is dead since 2019. If it ever has been fixed, it has been years ago. :grinning:

I am considering migrating to another active bot (sopel), however, might be worth to switch to a matrix-based or even discord-based bot framework.
